### PR TITLE
Updated total.js

### PR DESCRIPTION
**Pull request by gjaiswal108**

### CODE REVIEW

**Comment by gjaiswal108** [comment]
I saw, that total.js was outdated due to which there was UI error showing "processing", so I just ran the python program locally and updated the list.

**Comment by Surya1231** [comment]
Hey thank you for this

**Comment by Surya1231** [comment]
Hey but total for some contest vanished. Can you check for issue?

**Comment by Surya1231** [comment]
Update: I have taken care of that . Thank you

**Pull request merged**
